### PR TITLE
Prepare files for distribution with Vim

### PR DESCRIPTION
**Pull request by dkearns**
- syntax: fix syn-iskeyword version test
- syntax: remove special handling of Vim 5
- add standard Vim file headers
- ftplugin: only define maps if they have not been disabled by the user

### CODE REVIEW

**Review by benknoble — COMMENTED** [review]
Somehow I wasn't notified of this PR, but thanks for putting the time into this.

It's been hard for me to keep up with the current state-of-the-art for syntax files, so I definitely appreciate the cleanup here. Can we spell out `:highlight`, however? I'm a fan of using the full form in any script. I could do without the alignment of the 5th column of words, too, but I won't complain.

**Comment by dkearns** [comment]
Sorry I've been a bit sidetracked but I'll come back to it next week.  

I think using :highlight and losing the alignment will be fine.  In my experience, Bram is usually pretty relaxed about this sort of thing.  I think he is man who believes in filling the pan with larger fish.

You'll be joining an illustrious list of about half a dozen other rebel syntax file authors. :smile:

**Comment by benknoble** [comment]
Thanks for the updates. I plan to build a vimscript indentexpr for Racket, but it's a hefty undertaking and I don't currently have time allotted for it 😢

**Comment by dkearns** [comment]
I think you could include the Racket syntax, ftplugin, and indent files as they are now and get away with using the current filename based filetype detection.  It's definitely an improvement over defaulting to Scheme.

**Comment by dkearns** [comment]
Oh, there's also a `" Last Change: 2022 Aug 12` line included for each file at the end of the header block.

**Comment by dkearns** [comment]
> Thanks for the updates. I plan to build a vimscript indentexpr for Racket, but it's a hefty undertaking and I don't currently have time allotted for it cry

Supporting `formatprg` wouldn't be a bad start.

**Comment by benknoble** [comment]
> 



> Oh, there's also a `" Last Change: 2022 Aug 12` line included for each file at the end of the header block.

Do I write this myself or does Bram update it when including them? Asking because it's not in the PR but should be trivial for me to add after merging.

**Comment by benknoble** [comment]
> Supporting `formatprg` wouldn't be a bad start.

I'm looking at #4 for that. Certainly a faster path to a solution.

**Comment by dkearns** [comment]
> > 
> 
> > Oh, there's also a `" Last Change: 2022 Aug 12` line included for each file at the end of the header block.
> 
> Do I write this myself or does Bram update it when including them? Asking because it's not in the PR but should be trivial for me to add after merging.

Yes, it's a bit of a pain to version control and it often only has any real meaning when included in the Vim distribution so most of us just add it when we update Bram.

**Comment by benknoble** [comment]
I've got just one or two things to clean up, and then I'll send to vim/vim. Is a PR adding those files the right way to go (for a non-mailing-list expert)?

**Pull request merged**
